# Generated by Django 2.2.5 on 2019-12-15 09:20

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('hotmusic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TWEET',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_title', models.CharField(max_length=200)),
                ('t_artist', models.CharField(max_length=200)),
                ('t_day', models.CharField(max_length=20)),
                ('t_count', models.IntegerField()),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
